# Tags: 3.5-20211109-windowsservercore-2004
FROM dotnet/framework/sdk:3.5-20211109-windowsservercore-2004
FROM dotnet/framework/sdk:3.5-windowsservercore-2004
FROM dotnet/framework/sdk:4.8-3.5-windowsservercore-2004
