# Tags: 3.5-20211109-windowsservercore-20H2, 3.5-windowsservercore-2009, 3.5-windowsservercore-20H2
FROM mcr.microsoft.com/dotnet/framework/sdk:3.5-20211109-windowsservercore-20H2
FROM mcr.microsoft.com/dotnet/framework/sdk:3.5-windowsservercore-2009
FROM mcr.microsoft.com/dotnet/framework/sdk:3.5-windowsservercore-20H2
