# Tags: 3.5-windowsservercore-2009
FROM dotnet/framework/sdk:3.5-windowsservercore-2009
FROM dotnet/framework/sdk:3.5-windowsservercore-20H2
FROM dotnet/framework/sdk:3.5-20211109-windowsservercore-20H2
