# Tags: 3.5-20211109-windowsservercore-ltsc2016, 3.5-windowsservercore-ltsc2016
FROM mcr.microsoft.com/dotnet/framework/sdk:3.5-20211109-windowsservercore-ltsc2016
FROM mcr.microsoft.com/dotnet/framework/sdk:3.5-windowsservercore-ltsc2016
