# Tags: 3.5-20211109-windowsservercore-ltsc2019, 3.5-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/framework/sdk:3.5-20211109-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/framework/sdk:3.5-windowsservercore-ltsc2019
